name: Build and Install Virglrenderer, Mesa, and Viogpu3d

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_install:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2

    - name: Acquire and build Virglrenderer
      run: |
        git clone  https://gitlab.freedesktop.org/max8rr8/virglrenderer && cd virglrenderer
        mkdir install
        meson --prefix=$(pwd)/install build
        ninja -C build install
        export LD_LIBRARY_PATH=$(pwd)/install

    - name: Acquire and build Mesa
      run: |
        git clone --depth 10 --branch viogpu_win https://gitlab.freedesktop.org/max8rr8/mesa && cd mesa
        mkdir build && cd build
        $env:MESA_PREFIX="$PWD\mesa_prefix"
        meson .. --prefix=$env:MESA_PREFIX -Dgallium-drivers=virgl -Dgallium-d3d10umd=true -Dgallium-wgl-dll-name=viogpu_wgl -Dgallium-d3d10-dll-name=viogpu_d3d10 -Db_vscrt=mt
        ninja install

    - name: Acquire and build Viogpu3d
      run: |
        git clone --branch viogpu3d https://github.com/max8rr8/kvm-guest-drivers-windows && cd kvm-guest-drivers-windows
        cd viogpu
        # Optional: Setup test code signing from Visual Studio
        .\build_AllNoSdv.bat
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: kvm-guest-drivers-windows\viogpu\viogpu3d\objfre_win10_amd64\amd64\viogpu3d.exe
